require 'sidekiq'
require 'active_support/time'
require 'rack'
require 'airbrake'
require 'airbrake/sidekiq/error_handler'
require_relative '../config/environment'
get_db_connection()
require_relative '../config/initializers/redis'
require_relative '../config/initializers/airbrake'
require_relative 'workers'