# TODO : make development database

development:
  adapter: postgresql
  database: test
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: localhost

test:
  adapter: postgresql
  database: test
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: localhost

production:
  url: <%= ENV['DATABASE_URL'] %>
