
module STATUS_CODES
  SUCCESS               = 200
  CREATE_USER_SUCCESS   = 201
  MISSING_CREDENTIALS   = 400
  NO_MATCHING_SCHOOL    = 401
  NO_EXISTING_USER      = 402
  NO_VALID_ACCESS_TKN   = 403
  WRONG_PASSWORD        = 404
  WRONG_ACCESS_TKN_TYPE = 405
end
